/* EA DATABASE — sections finales (S116–S155) enregistrées dans EA.dbui.extra : analyse multi-marchés, ajout de match, performance, décisions, moteurs, contrôle final, dérive, erreurs, tableaux traçables. */
(function (g) {
  'use strict';
  var EA = g.EA; if (!EA || !EA.dbui || !EA.dbfinal || typeof document === 'undefined') return;
  var U = EA.dbui, H = U.h, F = EA.dbfinal, D = EA.database, esc = H.esc, kv = H.kv, card = H.card, pct = H.pct, st = H.st, S = H.S;
  var A = { home: '', away: '', lines: 'over:2.5 1.85 55\nbtts_yes 1.75', rp: null, add: null, msg: '' }, BADGE = { VALUE: '🔥 VALUE', CHECK: '🟡 CHECK', 'NO BET': '⚪ NO BET', BLOCKED: '🔴 BLOCKED' };
  function fd(iso) { return iso ? iso.slice(8, 10) + '/' + iso.slice(5, 7) + '/' + iso.slice(0, 4) : '—'; }
  function num(x) { var n = parseFloat(String(x).replace(',', '.')); return isFinite(n) ? n : null; }
  function bank() { try { var s = EA.storage.loadSettings(g.localStorage); return { bankroll: num(s.bankroll), minStake: num(s.minStake) }; } catch (e) { return {}; } }
  function ctx() { var recs = H.proRecs(), b = bank(), bt = EA.risk ? EA.risk.rulesBacktest(recs) : null, of = EA.dbintel.overfitting(bt, recs, 0); return { records: recs, bankroll: b.bankroll, minStake: b.minStake, overfit: of.risk }; }
  var CONF = { 'VERY LOW': 'Très faible', LOW: 'Faible', MODERATE: 'Moyen', GOOD: 'Bon', STRONG: 'Solide' };
  function statCard(name, r, test, ms) {
    if (!r || !r.n) return kv(name, 'N/A'); var tr = ms.filter(test), meta = st().meta(), per = ms.length ? fd(ms[0].date) + ' → ' + fd(ms[ms.length - 1].date) : '—';
    return '<details><summary>' + esc(name) + ' · ' + (r.pct * 100).toFixed(1) + ' % · N=' + r.n + ' · ' + CONF[r.level] + '</summary>' + kv('STAT', esc(name)) + kv('VALUE', (r.pct * 100).toFixed(1) + ' % (' + r.k + '/' + r.n + ')') + kv('N', r.n) + kv('PERIOD', per) + kv('CONFIDENCE', CONF[r.level]) + kv('SOURCE', 'EA DATABASE (interne)') + kv('LAST UPDATE', fd(meta.lastUpdate && meta.lastUpdate.slice(0, 10)))
      + '<p class="pro-dim">' + tr.length + ' match(s) composent cette statistique (20 plus récents) :</p>' + tr.slice(-20).reverse().map(function (m) { return kv(fd(m.date) + ' · ' + m.home + ' – ' + m.away, m.hs + '-' + m.as); }).join('') + '</details>';
  }
  var X = U.extra;
  X.ou = function (ms) { if (!ms.length) return card('📈 Over / Under', '<p class="pro-dim">N/A : aucune donnée.</p>'); var L = st().league(H.filt()), lines = ms[0].sport === 'basketball' ? D.CFG.ptLines : D.CFG.goalLines, h = '';
    lines.forEach(function (l) { h += statCard('Over ' + l, L.totals[l].over, function (m) { return m.hs + m.as > l; }, ms) + statCard('Under ' + l, L.totals[l].under, function (m) { return m.hs + m.as < l; }, ms); }); return card('📈 Over / Under', h + H.prov(ms)); };
  X.btts = function (ms) { if (!ms.length) return card('🎯 BTTS', '<p class="pro-dim">N/A : aucune donnée.</p>'); var L = st().league(H.filt()); if (!L.btts) return card('🎯 BTTS', '<p class="pro-dim">N/A pour ce sport.</p>'); var b = function (m) { return m.hs > 0 && m.as > 0; };
    return card('🎯 BTTS', statCard('BTTS Oui', L.btts.yes, b, ms) + statCard('BTTS Non', L.btts.no, function (m) { return !b(m); }, ms) + statCard('BTTS + Over 2.5', L.btts.yesOver25, function (m) { return b(m) && m.hs + m.as > 2.5; }, ms) + statCard('BTTS + Under 2.5', L.btts.yesUnder25, function (m) { return b(m) && m.hs + m.as < 2.5; }, ms) + H.prov(ms)); };
  X.inputs = function () {
    var f = '<div class="pro-fields"><input class="pro-in" id="edb2H" placeholder="Équipe domicile" value="' + esc(A.home || S.team) + '"><input class="pro-in" id="edb2A" placeholder="Équipe extérieur" value="' + esc(A.away || S.team2) + '"></div><textarea class="pro-in" id="edb2L" rows="4" placeholder="un marché par ligne : marché cote [proba modèle %]">' + esc(A.lines) + '</textarea>'
      + '<button class="pro-btn" onclick="EA.dbui2.run()">Analyser</button><p class="pro-dim">Marchés : over:1.5, over:2.5, over:3.5, btts_yes, home_win, draw, away_win. Laisser vide pour analyser les 7 marchés sans cote (NO BET « cote absente »). Compétition/sport : filtres du dessus. Seules les données antérieures à aujourd\'hui et à date fiable sont utilisées.</p>';
    var h = card('🧪 Model inputs · analyse multi-marchés', f); if (A.msg) h += '<p class="pro-dim">' + esc(A.msg) + '</p>'; var rp = A.rp; if (!rp) return h;
    var r0 = rp.results[0], best = rp.priorities[0] && rp.priorities[0].result, top = best ? best.decision : (rp.results.some(function (r) { return r.decision === 'CHECK'; }) ? 'CHECK' : 'NO BET'), ci = rp.input;
    h += card('MATCH', kv('Rencontre', esc(ci.home + ' – ' + ci.away)) + kv('Compétition', esc(ci.competition || 'toutes')) + kv('Cutoff anti-leakage', esc(r0.leak.cutoff) + ' ' + r0.leak.icon));
    h += card('DATA QUALITY · N · FRESHNESS', kv('Qualité', esc(r0.dq.band) + ' (' + r0.dq.score + '/100)') + kv('N', r0.dq.n) + kv('Fraîcheur', 'dernier match ' + fd(r0.dq.lastMatch)) + (r0.excludedApprox ? '<p class="pro-dim">' + r0.excludedApprox + ' match(s) à date approximative exclus.</p>' : ''));
    if (r0.cons && r0.cons.signals) h += card('MAIN SIGNALS', r0.cons.signals.map(function (s) { return kv(s.name, s.k == null ? pct(s.p) : esc(s.k + '/' + s.n) + ' → ' + pct(s.p)); }).join('') + (r0.matchup && r0.matchup.expected ? kv('Buts attendus (attaque × défense)', r0.matchup.expected.home.toFixed(2) + ' + ' + r0.matchup.expected.away.toFixed(2) + ' = ' + r0.matchup.expected.total.toFixed(2) + ' (ligue ' + r0.matchup.expected.leagueTotal.toFixed(2) + ')') : '') + '<p class="pro-dim">' + esc(r0.cons.provenance) + '</p>');
    h += card('MARKET ANALYSIS', rp.results.map(function (r, i) {
      var p = r.probabilities, ck = r.checks.map(function (c) { return '<li>' + (c.ok === true ? '✓' : c.ok === false ? '✗' : '–') + ' ' + esc(c.label) + (c.detail ? ' · ' + esc(c.detail) : '') + (c.ok === false && c.level === 'critical' ? ' <b>(critique)</b>' : '') + '</li>'; }).join('');
      return '<details><summary>' + BADGE[r.decision] + ' · ' + esc(F.MK[r.input.market] || r.input.market) + (p ? ' · ' + (p.final * 100).toFixed(1) + ' %' : '') + (r.input.odds ? ' @ ' + r.input.odds : '') + '</summary>' + (p ? kv('Modèle · implicite brute · normalisée · finale', [p.model, p.impliedRaw, p.normalized, p.final].map(function (v) { return v == null ? 'UNKNOWN' : (v * 100).toFixed(1) + ' %'; }).join(' · ')) + kv('Cote juste · cote minimale', r.fairOdds.toFixed(2) + ' · ' + r.minOdds.toFixed(2)) + kv('Edge · EV', (r.edgePts == null ? '—' : r.edgePts.toFixed(1) + ' pts') + ' · ' + (r.ev == null ? '—' : (r.ev * 100).toFixed(1) + ' %')) + kv('Confiance · risque', r.confidence.score + '/100 · ' + r.risk.level) + kv('Stabilité · conflit', (r.stability.available ? r.stability.stability + '/100' : '—') + ' · ' + (r.conflict.score == null ? '—' : r.conflict.score + '/100')) + kv('Incertitude', esc(r.uncertainty.note)) + '<p class="pro-dim">Facteurs indisponibles : ' + esc(r.confidence.unavailable.join(' ; ')) + '</p>' : '')
        + '<h3>FINAL DECISION GATE</h3><ul class="pro-list">' + ck + '</ul>' + kv('Position size', r.sizing.available ? r.sizing.stake.toFixed(2) + ' (plafonnée, sans garantie)' : esc(r.sizing.label) + ' · ' + esc(r.sizing.reason)) + '<p class="pro-dim">Pipeline : ' + r.pipeline.map(function (x) { return x.n + (x.status === 'ok' ? '✓' : x.status === 'n/a' ? '–' : '✗'); }).join(' ') + '</p>'
        + (r.input.odds > 1 ? '<button class="pro-btn small" onclick="EA.dbui2.save(' + i + ')">Enregistrer cette décision</button>' : '') + '</details>'; }).join(''));
    h += card('BEST OPPORTUNITIES', rp.priorities.length ? rp.priorities.map(function (x) { return kv(x.medal + ' · ' + esc(F.MK[x.result.input.market]), 'EV ' + (x.result.ev * 100).toFixed(1) + ' % · conf. ' + x.result.confidence.score + '/100'); }).join('') : '<p>Aucune opportunité suffisamment solide.</p>');
    var risks = {}, conf = {}, why = []; rp.results.forEach(function (r) { (r.risks || []).forEach(function (x) { risks[x] = 1; }); if (r.matchup) r.matchup.contradictions.forEach(function (x) { conf[x] = 1; }); }); if (best) why = best.why.concat(best.reasons);
    h += card('RISKS', Object.keys(risks).length ? '<ul class="pro-list">' + Object.keys(risks).map(function (x) { return '<li>' + esc(x) + '</li>'; }).join('') + '</ul>' : '<p class="pro-dim">Aucun risque spécifique relevé.</p>') + card('CONFLICTS', Object.keys(conf).length ? '<ul class="pro-list">' + Object.keys(conf).map(function (x) { return '<li>' + esc(x) + '</li>'; }).join('') + '</ul>' : '<p class="pro-dim">Aucune contradiction forte.</p>');
    h += card('WHY', (why.length ? '<ul class="pro-list">' + why.map(function (x) { return '<li>' + esc(x) + '</li>'; }).join('') + '</ul>' : '<p>' + esc(rp.results.map(function (r) { return r.reasons[0]; }).filter(Boolean).slice(0, 3).join(' · ') || '—') + '</p>') + '<p>' + esc(rp.choiceNote) + '</p>');
    h += card('FINAL DECISION', '<div class="pro-dec">' + (top === 'NO BET' ? '🚫 NO BET' : BADGE[top]) + '</div>' + (rp.combo ? '<h3>🔥 COMBINÉ RENTABLE</h3>' + rp.combo.legs.map(function (l, i) { return kv('Sélection ' + (i + 1), esc(l.market + ' ' + l.selection) + ' @ ' + l.odds); }).join('') + kv('Cote totale · probabilité jointe', rp.combo.odds.toFixed(2) + ' · ' + (rp.combo.pJoint * 100).toFixed(1) + ' %') + kv('EV (après incertitude)', (rp.combo.ev * 100).toFixed(1) + ' % (' + (rp.combo.evLow * 100).toFixed(1) + ' %)') + '<p class="pro-dim">« Rentable » = favorable selon le modèle et ses hypothèses, jamais un gain garanti. Corrélations provisoires.</p>' : '<p>' + esc(rp.comboText) + '</p>')); return h;
  };
  X.add = function () {
    var f = '<div class="pro-fields"><input class="pro-in" id="edbAd" placeholder="Date AAAA-MM-JJ"><input class="pro-in" id="edbAc" placeholder="Compétition" value="' + esc(S.comp) + '"><input class="pro-in" id="edbAh" placeholder="Domicile"><input class="pro-in" id="edbAa" placeholder="Extérieur"><input class="pro-in" id="edbAhs" inputmode="numeric" placeholder="Buts dom."><input class="pro-in" id="edbAas" inputmode="numeric" placeholder="Buts ext."><input class="pro-in" id="edbAch" inputmode="decimal" placeholder="Corners dom. (opt.)"><input class="pro-in" id="edbAca" inputmode="decimal" placeholder="Corners ext. (opt.)"><input class="pro-in" id="edbAsh" inputmode="decimal" placeholder="Tirs cadrés dom. (opt.)"><input class="pro-in" id="edbAsa" inputmode="decimal" placeholder="Tirs cadrés ext. (opt.)"></div><button class="pro-btn" onclick="EA.dbui2.addMatch()">Ajouter / mettre à jour</button><p class="pro-dim">Un champ vide reste UNKNOWN (jamais 0). Un match déjà connu est mis à jour, jamais dupliqué.</p>';
    var h = card('➕ Ajouter un match (pipeline complet)', f); if (A.add) h += card('Pipeline', A.add.steps.map(function (s) { return kv((s.ok ? '✓ ' : '✗ ') + s.step, esc(s.detail)); }).join('')); return h; };
  X.perf = function () { var recs = H.proRecs(), p = F.performance(recs, st().decisions()), f1 = function (v) { return v == null ? '—' : (v * 100).toFixed(1) + ' %'; };
    if (!p.n) return card('📈 EA PERFORMANCE', '<p class="pro-dim">' + esc(p.note) + '</p>');
    return card('📈 EA PERFORMANCE', kv('Paris réglés', p.n + ' · ' + esc(p.level)) + kv('Gagnés / perdus', p.won + ' / ' + p.lost) + kv('Taux de réussite', f1(p.hit)) + kv('ROI', f1(p.roi)) + kv('Profit / perte (unités)', p.profit.toFixed(2)) + kv('Pertes cumulées', p.totalLoss.toFixed(2)) + kv('Plus longue série de pertes', p.maxLosingStreak) + kv('Drawdown max', p.drawdown.toFixed(2) + ' u') + kv('EV annoncé moyen', f1(p.meanEV)) + kv('Brier · écart de calibration', (p.brier == null ? '—' : p.brier.toFixed(3)) + ' · ' + (p.ece == null ? '—' : (p.ece * 100).toFixed(1) + ' pts')) + kv('CLV', typeof p.clv === 'number' ? p.clv.toFixed(2) + ' pts' : esc(p.clv)) + '<p class="pro-dim">' + esc(p.note) + ' Les pertes sont affichées au même titre que les gains.</p>'); };
  X.decis = function () { var all = st().decisions().slice().reverse(), pg = S.page, pgs = Math.max(1, Math.ceil(all.length / 10));
    return card('🗂 Historique des décisions', (all.length ? all.slice(pg * 10, pg * 10 + 10).map(function (x) { var d = x.prediction; return '<div class="pro-kv"><span>' + fd(new Date(d.createdAt).toISOString().slice(0, 10)) + ' · ' + esc(d.match) + ' · ' + esc(F.MK[d.market] || d.market) + '</span><span>' + esc(d.decision) + (x.result ? ' · ' + (x.result.outcome === 'won' ? 'Gagné' : x.result.outcome === 'lost' ? 'Perdu' : 'Annulé') + ' (' + (x.result.profitUnits >= 0 ? '+' : '') + x.result.profitUnits.toFixed(2) + ' u)' : '') + '</span></div><p class="pro-dim">p ' + (d.p * 100).toFixed(1) + ' % · cote ' + d.odds + ' · cote juste ' + d.fair.toFixed(2) + ' · edge ' + (d.edgePts == null ? '—' : d.edgePts.toFixed(1)) + ' pts · EV ' + (d.ev * 100).toFixed(1) + ' % · confiance ' + d.confidence + ' · risque ' + esc(d.risk) + (st().verifyDecision(d) ? ' · ✅ intact' : ' · ⚠️ altérée') + '</p>' + (x.result || d.decision === 'NO BET' ? '' : '<button class="pro-btn small" onclick="EA.dbui2.settle(\'' + d.id + '\',\'won\')">Gagné</button> <button class="pro-btn small" onclick="EA.dbui2.settle(\'' + d.id + '\',\'lost\')">Perdu</button> <button class="pro-btn small" onclick="EA.dbui2.settle(\'' + d.id + '\',\'void\')">Annulé</button>'); }).join('') : '<p class="pro-dim">Aucune décision enregistrée. Utilisez « Enregistrer cette décision » dans 🧪 Analyse.</p>') + H.pager(pg, pgs) + '<p class="pro-dim">La prédiction est figée ; le résultat est stocké à part et ne la modifie jamais.</p>'); };
  X.engines = function () { var rg = F.registry(st(), H.proRecs()), ic = { ACTIVE: '🟢', PARTIAL: '🟡', UNAVAILABLE: '🔴', 'INSUFFICIENT DATA': '⚪' };
    return card('🧰 Moteurs : réalité du code', rg.map(function (x) { return kv(ic[x.status] + ' ' + x.engine, esc(x.status)) + '<p class="pro-dim">' + esc(x.detail) + '</p>'; }).join('')) + card('Couches', F.layers().map(function (l) { return kv((l.status === 'ACTIVE' ? '🟢 ' : '🔴 ') + l.layer, esc(l.status)) + '<p class="pro-dim">' + esc(l.detail) + '</p>'; }).join('')); };
  X.drift = function () { var d = F.drift(st(), { sport: S.sport || undefined, competition: S.comp || undefined }, H.proRecs()); return card('🌊 Surveillance de dérive', d.items.length ? d.items.map(function (x) { return kv(x.metric, x.nHist ? x.hist.toFixed(2) + ' (N=' + x.nHist + ') → ' + x.recent.toFixed(2) + ' (N=' + x.nRecent + ')' : x.hist.toFixed(3) + ' → ' + x.recent.toFixed(3)) + (x.shift ? '<p>' + d.label + '</p>' : ''); }).join('') + '<p class="pro-dim">' + esc(d.note) + '</p>' : '<p class="pro-dim">Échantillon insuffisant (minimum 40 observations par statistique).</p>'); };
  X.errors = function () { var e = F.errorPatterns(H.proRecs()); return card('🧠 Mémoire des erreurs', (e.patterns.length ? e.patterns.map(function (p) { return kv((p.pattern ? '🔁 PATTERN · ' : '') + p.marche + ' · ' + p.categorie, p.count + ' / N=' + p.n) + '<p class="pro-dim">' + esc(p.note) + '</p>'; }).join('') : '<p class="pro-dim">Aucun résultat perdu enregistré.</p>') + (e.errors.length ? '<details><summary>' + e.errors.length + ' erreur(s) détaillée(s)</summary>' + e.errors.slice(-15).reverse().map(function (x) { return kv(x.date + ' · ' + x.marche, esc(x.championnat) + ' · p ' + (x.prediction * 100).toFixed(0) + ' % · ' + esc(x.contexte)); }).join('') + '</details>' : '') + '<p class="pro-dim">EA apprend des patterns répétés (N ≥ 30, ≥ 3 occurrences, ≥ 40 % des pertes), jamais d\'un résultat isolé.</p>'); };
  X.final = function () { var chk = F.selfCheck(), m = st().meta(), recs = H.proRecs(), bt = EA.risk ? EA.risk.rulesBacktest(recs) : null, ss = EA.dbintel.systemStatus(st(), recs, bt), ic = function (n) { return (ss.filter(function (x) { return x.name === n; })[0] || {}).icon || '⚪'; };
    var ready = m.state === 'READY', mods = F.registry(st(), recs).filter(function (x) { return x.status === 'ACTIVE'; }).length;
    var ban = '<div class="pro-card"><h3>🧠 EA-VALUE · STATISTICAL INTELLIGENCE SYSTEM</h3>' + kv('📊 DATABASE', ready ? '🟢 READY' : '⚪ VIDE') + kv('⚙️ MODELS', mods + ' moteur(s) ACTIVE · ' + ic('MODELS')) + kv('🎯 DECISION ENGINE', EA.dbfinal.layers().every(function (l) { return l.status === 'ACTIVE'; }) ? '🟢 READY' : '🔴 INCOMPLET') + kv('🛡 RISK ENGINE', EA.risk ? '🟢 READY' : '🔴 INDISPONIBLE') + '<p class="pro-dim">Aucun 🟢 simulé : voir EA SYSTEM STATUS (aperçu).</p></div>';
    return ban + card('✅ Contrôle final (exécuté maintenant)', chk.map(function (c) { return kv(c.status + ' ' + c.name, esc(c.detail || '')); }).join('') + '<p class="pro-dim">Exécuté sur un jeu de test synthétique en mémoire ; ne modifie pas vos données. ⚪ = non vérifiable depuis l\'application.</p>')
      + card('Versions', kv('Application', 'EA-VALUE Pro 3.0') + kv('Database', esc(m.name) + ' · schéma ' + m.schema) + kv('Model engine', esc(m.model)) + kv('Paramètres', esc(m.params)) + kv('Dernier rebuild', esc(m.lastRebuild || '—')) + kv('Dernière mise à jour', esc(m.lastUpdate || '—')) + kv('Données', m.matches + ' matchs · ' + m.competitions + ' compétition(s) · ' + m.teams + ' équipe(s)') + (m.versions || []).slice(-5).reverse().map(function (v) { return kv(v.t.slice(0, 16).replace('T', ' '), 'db v' + v.db + ' · ' + v.matches + ' matchs'); }).join('')); };
  var T = '';
  EA.dbui2 = {
    run: function () { var v = function (id) { var e = document.getElementById(id); return e ? e.value : ''; }; A.home = v('edb2H').trim(); A.away = v('edb2A').trim(); A.lines = v('edb2L'); A.msg = '';
      try { var lines = A.lines.split(/\n+/).map(function (l) { var p = l.trim().split(/\s+/); if (!p[0]) return null; var mp = num(p[2]); return { market: p[0], odds: num(p[1]), modelP: mp == null ? null : mp / 100 }; }).filter(Boolean); A.rp = F.report(st(), { sport: S.sport || 'football', competition: S.comp || undefined, home: A.home, away: A.away }, lines, ctx()); st().log('MODEL', 'Rapport ' + A.home + ' – ' + A.away + ' (' + lines.length + ' marché(s))'); st().saveNow(); }
      catch (e) { A.rp = null; A.msg = 'Analyse impossible : ' + e.message; } H.render(); },
    save: function (i) { var r = A.rp && A.rp.results[i]; if (!r || !r.probabilities) return; st().addDecision({ match: A.home + ' – ' + A.away, competition: S.comp || '', sport: S.sport || 'football', market: r.input.market, p: r.probabilities.final, odds: r.input.odds, fair: r.fairOdds, edgePts: r.edgePts, ev: r.ev, confidence: r.confidence.score, risk: r.risk.level, decision: r.decision, engine: EA.core ? EA.core.VERSION : '?', db: st().meta().name }); A.msg = 'Décision enregistrée (figée) — voir 🗂 Décisions.'; H.render(); },
    settle: function (id, o) { st().settleDecision(id, o, 1); H.render(); },
    addMatch: function () { var v = function (id) { var e = document.getElementById(id); return e ? e.value.trim() : ''; }, num_ = function (id) { return v(id) === '' ? null : num(v(id)); }; var row = { sport: S.sport || 'football', date: v('edbAd'), competition: v('edbAc'), home: v('edbAh'), away: v('edbAa'), hs: v('edbAhs') === '' ? null : v('edbAhs'), as: v('edbAas') === '' ? null : v('edbAas'), source: 'MANUAL', corners_h: num_('edbAch'), corners_a: num_('edbAca'), sot_h: num_('edbAsh'), sot_a: num_('edbAsa') };
      try { A.add = F.addMatch(st(), row, { records: H.proRecs() }); } catch (e) { A.add = { steps: [{ step: 'ERREUR', detail: e.message, ok: false }] }; } H.render(); } };
  U.extraSecs.push(['add', '➕ Ajouter'], ['perf', '📈 Performance'], ['decis', '🗂 Décisions'], ['engines', '🧰 Moteurs'], ['drift', '🌊 Dérive'], ['final', '✅ Contrôle final']);
})(typeof window !== 'undefined' ? window : global);
