/* EA DATABASE — onglet 📊 (espace séparé). Aucune donnée inventée : absent = UNKNOWN. */
(function (g) {
  'use strict';
  var EA = g.EA; if (!EA || !EA.database || typeof document === 'undefined') return;
  var D = EA.database, store = null, S = { sec: 'overview', page: 0, inp: { market: 'over:2.5' }, analysis: null, sport: '', comp: '', season: '', team: '', team2: '', venue: '', last: '', csv: '', log: null, q: '' };
  function esc(s) { return String(s == null ? '' : s).replace(/[&<>"]/g, function (c) { return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]; }); }
  function st() { if (!store) store = D.createStore(g.localStorage); return store; }
  function pct(v) { return v == null ? 'UNKNOWN' : (v * 100).toFixed(0) + ' %'; }
  function a2(x, d) { return x && x.avg != null ? x.avg.toFixed(d || 2) + ' (n=' + x.n + ')' : 'UNKNOWN'; }
  function kv(l, v) { return '<div class="pro-kv"><span>' + esc(l) + '</span><span>' + v + '</span></div>'; }
  function rowsR(rows) { return rows.map(function (r) { return kv(r[0], esc(D.fmt(r[1])) + ' · ' + esc(r[1].level)); }).join(''); }
  function card(t, b) { return '<div class="pro-card"><h3>' + t + '</h3>' + b + '</div>'; }
  function linesHtml(L) { return Object.keys(L).map(function (l) { return kv('Over ' + l, esc(D.fmt(L[l].over))) + kv('Under ' + l, esc(D.fmt(L[l].under))); }).join(''); }
  function filt() { var f = { sport: S.sport || undefined, competition: S.comp || undefined, season: S.season || undefined, venue: S.venue || undefined }; if (S.last) f.last = +S.last; return f; }
  function prov(ms) { var m = st().meta(); return '<p class="pro-dim">Source : EA DATABASE · ' + ms.length + ' match(s) utilisé(s) · période ' + (ms.length ? ms[0].date + ' → ' + ms[ms.length - 1].date : '—') + ' · dernière mise à jour ' + esc(m.lastUpdate ? m.lastUpdate.slice(0, 10) : '—') + '</p>'; }
  function opts(vals, cur, all) { return '<option value="">' + all + '</option>' + vals.map(function (v) { return '<option' + (v === cur ? ' selected' : '') + '>' + esc(v) + '</option>'; }).join(''); }
  function uniq(ms, k) { var o = {}; ms.forEach(function (m) { if (m[k]) o[m[k]] = 1; }); return Object.keys(o).sort(); }

  function proRecs() { try { var raw = JSON.parse(g.localStorage.getItem('ea_pro_memory')); return raw && raw.analyses || []; } catch (e) { return []; } }
  function pairLine(x) { if (x.unknown) return kv(x.name, 'UNKNOWN'); return x.team && x.team.pct != null ? kv(x.name, esc(D.fmt(x.team)) + ' vs ligue ' + pct(x.league.pct) + ' · ' + (x.diffPts >= 0 ? '+' : '') + x.diffPts.toFixed(1) + ' pts (shrink ' + (x.shrunkPts >= 0 ? '+' : '') + x.shrunkPts.toFixed(1) + ')') : kv(x.name, 'ratio ' + x.ratio.toFixed(2) + ' (shrink ' + x.shrunkRatio.toFixed(2) + ') · N=' + x.n); }
  var BADGE = { VALUE: '🔥 VALUE', CHECK: '🟡 CHECK', 'NO BET': '⚪ NO BET', BLOCKED: '🔴 BLOCKED' };
  function analysisHtml() {
    var I = EA.dbintel, i = S.inp, f = '<div class="pro-fields"><input class="pro-in" id="edbH" placeholder="Équipe domicile" value="' + esc(i.home || S.team) + '"><input class="pro-in" id="edbA" placeholder="Équipe extérieur" value="' + esc(i.away || S.team2) + '"><select class="pro-in" id="edbM">' + ['over:1.5', 'over:2.5', 'over:3.5', 'btts_yes', 'home_win', 'draw', 'away_win'].map(function (m) { return '<option' + (m === i.market ? ' selected' : '') + '>' + m + '</option>'; }).join('') + '</select>'
      + '<input class="pro-in" id="edbP" inputmode="decimal" placeholder="Proba modèle % (optionnel)" value="' + esc(i.p || '') + '"><input class="pro-in" id="edbO" inputmode="decimal" placeholder="Cote bookmaker" value="' + esc(i.odds || '') + '"><input class="pro-in" id="edbOO" placeholder="Autres cotes du marché (ex: 1.35)" value="' + esc(i.oo || '') + '"></div><button class="pro-btn" onclick="EA.dbui.analyze()">Analyser</button><p class="pro-dim">Compétition/sport : filtres ci-dessus. Seules les données antérieures à aujourd\'hui et à date fiable sont utilisées.</p>';
    var R = S.analysis, h = card('🧪 Model inputs · analyse', f); if (!R) return h;
    var b = '<div class="pro-dec">' + BADGE[R.decision] + '</div>' + kv('DATA LEAKAGE CHECK', esc(R.leak.icon) + ' (' + R.leak.used + ' matchs < ' + esc(R.leak.cutoff) + (R.excludedApprox ? ' · ' + R.excludedApprox + ' à date approx. exclus' : '') + ')') + kv('Qualité des données', esc(R.dq.band) + ' · ' + R.dq.score + '/100 · N=' + R.dq.n);
    b += R.reasons.map(function (x) { return '<p><b>' + (R.decision === 'VALUE' ? 'Raison' : 'RAISON') + ' :</b> ' + esc(x) + '</p>'; }).join('');
    if (R.probabilities) { var p = R.probabilities, f1 = function (v) { return v == null ? 'UNKNOWN' : (v * 100).toFixed(1) + ' %'; };
      b += '<h3>Probabilités (séparées)</h3>' + kv('Modèle', f1(p.model)) + kv('Implicite brute (marge incluse)', f1(p.impliedRaw)) + kv('Implicite normalisée', p.normalized == null ? 'non calculable (une seule cote)' : f1(p.normalized) + ' · overround ' + p.overround.toFixed(1) + ' %') + kv('Ajustée / finale (EA DATABASE + modèle)', f1(p.final))
        + kv('Cote juste · cote minimale', R.fairOdds.toFixed(2) + ' · ' + R.minOdds.toFixed(2)) + kv('Edge · EV', (R.edgePts == null ? '—' : R.edgePts.toFixed(1) + ' pts') + ' · ' + (R.ev == null ? '—' : (R.ev * 100).toFixed(1) + ' %')) + kv('Incertitude', esc(R.uncertainty.note)) + kv('Stabilité', R.stability.available ? esc(R.stability.label) + ' (' + R.stability.stability + '/100, ' + R.stability.variants + ' variantes)' : '—') + kv('Conflit', esc(R.conflict.label) + (R.conflict.score != null ? ' (' + R.conflict.score + '/100)' : ''))
        + kv('EA CONFIDENCE', R.confidence.score + '/100') + '<p class="pro-dim">' + esc(R.confidence.note) + '</p><h3>Sources internes</h3>' + R.cons.signals.map(function (s) { return kv(s.name, s.k == null ? pct(s.p) : esc(s.k + '/' + s.n) + ' → ' + pct(s.p) + ' (shrink)'); }).join('') + '<p class="pro-dim">' + esc(R.cons.provenance) + '</p>'; }
    if (R.why.length) b += '<h3>POURQUOI ?</h3><ul class="pro-list">' + R.why.map(function (x) { return '<li>' + esc(x) + '</li>'; }).join('') + '</ul>'; if (R.risks.length) b += '<h3>RISQUES</h3><ul class="pro-list">' + R.risks.map(function (x) { return '<li>' + esc(x) + '</li>'; }).join('') + '</ul>';
    if (R.decision === 'NO BET' || R.decision === 'CHECK') b += '<h3>POURQUOI PAS ?</h3><p>' + esc(R.reasons.join(' · ')) + '</p>';
    return h + card('Résultat · ' + esc(S.analysis.input.market), b);
  }
  function section(ms) {
    var I = EA.dbintel, recs = proRecs(), s0 = st(), f0 = filt(); delete f0.last;
    var X = EA.dbui && EA.dbui.extra && EA.dbui.extra[S.sec]; if (X) return X(ms);
    if (I && S.sec === 'overview') { var bt = EA.risk ? EA.risk.rulesBacktest(recs) : null, ss = I.systemStatus(s0, recs, bt), tsr = I.trendShift(s0, { sport: S.sport || undefined, competition: S.comp || undefined }), dq = I.dataQuality(s0, f0);
      return card('🗂 EA SYSTEM STATUS', ss.map(function (x) { return kv(x.icon + ' ' + x.name, esc(x.detail)); }).join('') + '<p class="pro-dim">Aucun 🟢 n\'est simulé : chaque ligne reflète l\'état réel.</p>') + card('Qualité & intégrité', kv('Qualité de la base', esc(dq.band) + ' · ' + dq.score + '/100 (N=' + dq.n + ')') + kv('DATA LEAKAGE CHECK', '🟢 SAFE (mode strict : date fiable < date du match)') + kv('Doublons probables (DUPLICATE CANDIDATE)', s0.meta().duplicates) + kv('Quarantaine', s0.meta().quarantined))
        + card('Surveillance (tendances)', tsr.items.length ? tsr.items.map(function (x) { return kv(x.metric, pct(x.hist) + ' (N=' + x.nHist + ') → ' + pct(x.recent) + ' (N=' + x.nRecent + ')' + (x.shift ? ' · ⚠️ TREND SHIFT DETECTED' : '')); }).join('') + '<p class="pro-dim">' + esc(tsr.note) + '</p>' : '<p class="pro-dim">' + esc(tsr.note) + '</p>'); }
    if (I && S.sec === 'quality') { var q = I.dataQuality(s0, f0), names = { sample: 'Taille d\'échantillon', freshness: 'Fraîcheur', completeness: 'Complétude (corners/SOT/tirs)', diversity: 'Diversité', consistency: 'Cohérence', coverage: 'Couverture dom./ext.', recent: 'Couverture récente', stability: 'Stabilité', provenance: 'Provenance (dates fiables)' };
      return card('✅ Qualité des données', kv('Score', q.score + '/100 · ' + esc(q.band)) + Object.keys(q.dims).map(function (k) { return kv(names[k] || k, q.dims[k].toFixed(0) + '/100'); }).join('') + (q.note ? '<p class="pro-dim">' + esc(q.note) + '</p>' : '') + '<p class="pro-dim">Une faible complétude (corners, tirs) reste UNKNOWN : elle réduit le score, elle n\'est jamais remplie.</p>'); }
    if (I && S.sec === 'base') { if (!S.team.trim()) { var L0 = ms.length ? s0.league(filt()) : null; return card('📏 Baselines', L0 ? kv('Buts/match', a2(L0.goals)) + rowsR([['Home win', L0.result.home], ['Draw', L0.result.draw], ['Away win', L0.result.away]]) + (L0.btts ? rowsR([['BTTS', L0.btts.yes], ['Over 1.5', L0.totals[1.5].over], ['Over 2.5', L0.totals[2.5].over], ['Under 2.5', L0.totals[2.5].under]]) : '') + '<p class="pro-dim">Saisissez une équipe pour la comparer à cette baseline.</p>' + prov(ms) : '<p class="pro-dim">Aucune donnée.</p>'); }
      var tv = I.teamVsLeague(s0, S.team.trim(), { sport: S.sport || undefined, competition: S.comp || undefined, season: S.season || undefined }); return card('📏 ' + esc(S.team) + ' vs baseline du championnat', tv.items.length ? tv.items.map(pairLine).join('') + '<p class="pro-dim">' + esc(tv.note) + '</p>' + prov(ms) : '<p class="pro-dim">Données insuffisantes.</p>'); }
    if (I && S.sec === 'inputs') return analysisHtml();
    if (I && S.sec === 'health') { var mh = I.modelHealth(recs), bt2 = EA.risk ? EA.risk.rulesBacktest(recs) : null, of = I.overfitting(bt2, recs, 0);
      return card('🩺 MODEL HEALTH', (mh.length ? mh.map(function (x) { return kv(x.icon + ' ' + x.key, x.status + ' · N=' + x.n) + '<p class="pro-dim">Brier ' + x.brier.toFixed(3) + ' (récent ' + x.brierRecent.toFixed(3) + ') · écart annoncé/réel ' + (x.gap * 100).toFixed(0) + ' pts · ' + esc(x.version) + ' · ' + x.lastUpdate + '</p>'; }).join('') : '<p class="pro-dim">⚪ Aucun résultat réglé : aucun moteur ne peut être jugé.</p>')) + card('Versions & évolution', kv('Version modèle', esc(EA.core ? EA.core.VERSION : '?')) + kv('Version database', esc(s0.meta().name)) + kv('Version paramètres', 'p1 (règles fixées a priori)') + '<p class="pro-dim">Tout changement de poids/modèle n\'est adopté qu\'après test hors échantillon (ADOPT sinon ROLLBACK). Aucune modification automatique active.</p>') + card('Anti-overfitting', kv('État', esc(of.label || of.note)) + (of.alerts || []).map(function (a) { return '<p>⚠️ ' + esc(a) + '</p>'; }).join('')); }
    if (S.sec === 'journal') { var j = s0.journal().slice().reverse(), pg = S.page, pgs = Math.max(1, Math.ceil(j.length / 15)); return card('🧾 Data history · journal', j.slice(pg * 15, pg * 15 + 15).map(function (e) { return kv(e.t.slice(0, 16).replace('T', ' ') + ' · ' + e.type, esc(e.msg)); }).join('') + (j.length ? '' : '<p class="pro-dim">Aucun événement.</p>') + pager(pg, pgs)); }
    if (S.sec === 'errors') { var em = EA.postmortem ? EA.postmortem.errorMemory(recs.filter(function (r) { return r.type !== 'combo'; })) : { groups: {} }, ks = Object.keys(em.groups); return card('🧠 Error memory', ks.length ? ks.map(function (k) { var x = em.groups[k]; return kv(k, x.won + 'G/' + x.lost + 'P (N=' + x.n + ')') + '<p class="pro-dim">' + esc(x.caution) + (x.frequentError ? ' · erreur fréquente : ' + esc(x.frequentError) : '') + '</p>'; }).join('') : '<p class="pro-dim">Aucun résultat réglé.</p>'); }
    if (S.sec === 'search') { var q2 = D.norm(S.q), res = '';
      if (q2.length < 2) res = '<p class="pro-dim">Tapez au moins 2 caractères (équipe, compétition, pays, saison, match).</p>'; else {
        var all = s0.played({}), comps = {}, tms = {}, seas = {}; all.forEach(function (m) { if (D.norm(m.competition).indexOf(q2) >= 0 || D.norm(m.country).indexOf(q2) >= 0) comps[m.competition] = (comps[m.competition] || 0) + 1; if (m.season && m.season.indexOf(q2) >= 0) seas[m.season] = (seas[m.season] || 0) + 1; [m.home, m.away].forEach(function (t) { if (D.norm(t).indexOf(q2) >= 0) tms[t] = (tms[t] || 0) + 1; }); });
        var mm = all.filter(function (m) { return D.norm(m.home + ' ' + m.away).indexOf(q2) >= 0; }).slice(-10).reverse();
        res = Object.keys(comps).slice(0, 8).map(function (c) { return '<div class="pro-kv"><button class="pro-btn small" data-edbset="comp:' + esc(c) + '">' + esc(c) + '</button><span>' + comps[c] + ' matchs</span></div>'; }).join('') + Object.keys(seas).slice(0, 5).map(function (c) { return '<div class="pro-kv"><button class="pro-btn small" data-edbset="season:' + esc(c) + '">Saison ' + esc(c) + '</button><span>' + seas[c] + ' matchs</span></div>'; }).join('') + Object.keys(tms).slice(0, 12).map(function (t) { return '<div class="pro-kv"><button class="pro-btn small" data-edbset="team:' + esc(t) + '">' + esc(t) + '</button><span>' + tms[t] + ' matchs</span></div>'; }).join('') + mm.map(function (m) { return kv(m.date + ' · ' + m.home + ' – ' + m.away, m.hs + '-' + m.as); }).join('') || '<p class="pro-dim">Aucun résultat.</p>'; }
      return card('🔎 Recherche', '<div class="pro-fields"><input class="pro-in" id="edbQ2" placeholder="équipe, compétition, pays, saison, match" value="' + esc(S.q) + '"></div>' + res); }
    return section0(ms);
  }
  function safeSection(ms) { try { return section(ms); } catch (e) { try { st().log('ERROR', 'Section ' + S.sec + ' : ' + e.message); st().saveNow(); } catch (e2) { } return card('⚠️ Erreur d\'affichage', '<p>Cette section n\'a pas pu être calculée (' + esc(e.message) + '). Les données ne sont pas modifiées ; l\'incident est dans le journal.</p>'); } }
  function pager(pg, pgs) { return '<div class="pro-row"><button class="pro-btn small" data-edbpage="' + (pg - 1) + '"' + (pg <= 0 ? ' disabled' : '') + '>◀</button><span class="pro-dim">page ' + (pg + 1) + '/' + pgs + '</span><button class="pro-btn small" data-edbpage="' + (pg + 1) + '"' + (pg + 1 >= pgs ? ' disabled' : '') + '>▶</button></div>'; }
  function section0(ms) {
    var s = st(), L = ms.length ? s.league(filt()) : null, tname = S.team.trim(), T = tname ? s.team(tname, filt()) : null;
    if (S.sec === 'comp') {
      var by = {}; ms.forEach(function (m) { var k = m.sport + ' · ' + (m.country ? m.country + ' · ' : '') + (m.competition || '—') + ' · ' + m.season; by[k] = (by[k] || 0) + 1; });
      var h = Object.keys(by).sort().map(function (k) { return kv(k, by[k] + ' match(s) · ' + D.level(by[k])); }).join('') || '<p class="pro-dim">Aucune donnée : importez un CSV ou reconstruisez depuis l\'historique.</p>';
      if (L && L.n) h += '<hr><h3>League dashboard</h3>' + kv('Matches', L.n + ' · ' + L.level) + kv(L.goals.avg != null && ms[0].sport === 'basketball' ? 'Points / match' : 'Buts / match', a2(L.goals)) + rowsR([['Home win', L.result.home], ['Draw', L.result.draw], ['Away win', L.result.away]])
        + (L.btts ? rowsR([['BTTS', L.btts.yes], ['Over 1.5', L.totals[1.5].over], ['Over 2.5', L.totals[2.5].over], ['Over 3.5', L.totals[3.5].over], ['Over 4.5', L.totals[4.5].over]]) + kv('Corners', a2(L.corners.total)) + kv('SOT', a2(L.sot.total)) : '');
      return card('📚 Compétitions', h + prov(ms));
    }
    if (S.sec === 'teams') {
      var q = D.norm(S.q), names = {}; ms.forEach(function (m) { [m.home, m.away].forEach(function (t) { if (!q || D.norm(t).indexOf(q) >= 0) names[t] = (names[t] || 0) + 1; }); });
      var list = Object.keys(names).sort().slice(0, 30).map(function (t) { return kv(t, names[t] + ' match(s)') ; }).join('');
      var h2 = '<div class="pro-fields"><input class="pro-in" id="edbQ" placeholder="Rechercher équipe, compétition, pays" value="' + esc(S.q) + '"></div>' + (list || '<p class="pro-dim">Aucune équipe trouvée.</p>');
      if (T && T.n) h2 += '<hr><h3>Team dashboard · ' + esc(T.team) + '</h3>' + ['global', 'home', 'away'].map(function (k) { var b = T[k]; return '<h3>' + k.toUpperCase() + ' · ' + b.n + ' (' + b.level + ')</h3>' + kv('V/N/D', b.W + '/' + b.D + '/' + b.L) + kv('GF/G · GA/G', a2(b.gf) + ' · ' + a2(b.ga)) + kv('BTTS', esc(D.fmt(b.btts))) + kv('Over 2.5', esc(D.fmt(b.over[2.5]))) + kv('Clean sheets', esc(D.fmt(b.cleanSheets))) + kv('Corners / SOT / tirs (pour)', a2(b.corners.for, 1) + ' · ' + a2(b.sot.for, 1) + ' · ' + a2(b.shots.for, 1)); }).join('') + kv('Forme (5 derniers)', esc(T.global.form || 'UNKNOWN'));
      return card('⚽ Équipes', h2 + prov(ms));
    }
    if (!L) return card('Aucune donnée', '<p class="pro-dim">Aucun match ne correspond aux filtres.</p>');
    if (S.sec === 'goals') return card('🥅 Buts', kv('Total moyen', a2(L.goals)) + kv('Domicile / Extérieur', a2(L.goalsHome) + ' · ' + a2(L.goalsAway)) + linesHtml(L.totals) + prov(ms));
    if (S.sec === 'btts') return card('🎯 BTTS', L.btts ? rowsR([['BTTS Oui', L.btts.yes], ['BTTS Non', L.btts.no], ['BTTS + Over 2.5', L.btts.yesOver25], ['BTTS + Under 2.5', L.btts.yesUnder25]]) + prov(ms) : '<p class="pro-dim">Non applicable à ce sport.</p>');
    if (S.sec === 'ou') return card('📈 Over / Under', linesHtml(L.totals) + prov(ms));
    if (S.sec === 'ha') { var r = L.result; return card('🏠 Domicile / Extérieur', rowsR([['Home win', r.home], ['Draw', r.draw], ['Away win', r.away], ['Home ou nul', r.homeOrDraw], ['Away ou nul', r.awayOrDraw], ['Home ou away', r.homeOrAway]]) + (T && T.n ? '<hr>' + ['home', 'away'].map(function (k) { var b = T[k]; return kv(k === 'home' ? 'Domicile' : 'Extérieur', b.W + 'V ' + b.D + 'N ' + b.L + 'D · ' + a2(b.gf) + ' marqués · ' + a2(b.ga) + ' encaissés (n=' + b.n + ')'); }).join('') : '<p class="pro-dim">Saisissez une équipe (filtre) pour séparer global / domicile / extérieur.</p>') + prov(ms)); }
    if (S.sec === 'corners' || S.sec === 'sot' || S.sec === 'shots') { var k = S.sec, B = L[k]; if (!B) return card('Non applicable', '<p class="pro-dim">Statistique non définie pour ce sport.</p>'); return card({ corners: '🚩 Corners', sot: '🎯 Tirs cadrés', shots: '🎯 Tirs' }[k], kv('Moyenne totale', a2(B.total)) + kv('Domicile', a2(B.home)) + kv('Extérieur', a2(B.away)) + linesHtml(B.lines) + (B.total.n === 0 ? '<p class="pro-dim">⚠️ Donnée UNKNOWN : aucun match ne contient cette statistique.</p>' : '') + prov(ms)); }
    if (S.sec === 'form' || S.sec === 'trends') {
      if (!T || !T.n) return card('Choisissez une équipe', '<p class="pro-dim">Saisissez une équipe dans le filtre « Équipe ».</p>');
      var tr = Object.keys(T.trends).map(function (w) { var x = T.trends[w]; return '<h3>' + (w === 'all' ? 'Historique' : w + ' derniers') + '</h3>' + kv('Over 2.5', esc(D.fmt(x.over25))) + kv('BTTS', esc(D.fmt(x.btts))) + kv('Corners > 9.5', esc(D.fmt(x.corners95))); }).join('');
      var sk = Object.keys(T.streaks).filter(function (x) { return x !== 'note'; }).map(function (x) { return kv('Série ' + x, String(T.streaks[x])); }).join('');
      return card(S.sec === 'form' ? '📊 Formes · ' + esc(T.team) : '🧠 Tendances · ' + esc(T.team), (S.sec === 'form' ? kv('5 derniers', esc(T.global.form)) + kv('Global', T.global.n + ' · ' + T.global.level) : '') + tr + (S.sec === 'trends' ? '<hr>' + sk + '<p class="pro-dim">' + esc(T.streaks.note) + '</p>' : '') + prov(ms));
    }
    if (S.sec === 'h2h') {
      if (!S.team.trim() || !S.team2.trim()) return card('🔎 H2H', '<p class="pro-dim">Saisissez les deux équipes (filtres « Équipe » et « Adversaire »).</p>');
      var a = D.norm(S.team), b = D.norm(S.team2), h = ms.filter(function (m) { var x = D.norm(m.home), y = D.norm(m.away); return (x === a && y === b) || (x === b && y === a); }), cut = new Date(); cut.setFullYear(cut.getFullYear() - 3); var cs = cut.toISOString().slice(0, 10);
      var blk = function (arr, t) { return arr.length ? '<h3>' + t + ' (' + arr.length + ')</h3>' + arr.slice(-8).map(function (m) { return kv(m.date + ' · ' + m.home + ' – ' + m.away, m.hs + '-' + m.as); }).join('') : '<h3>' + t + '</h3><p class="pro-dim">UNKNOWN</p>'; };
      return card('🔎 H2H', blk(h.filter(function (m) { return m.date >= cs; }), 'H2H récent (3 ans)') + blk(h.filter(function (m) { return m.date < cs; }), 'H2H ancien (poids réduit)') + prov(h));
    }
    if (S.sec === 'hist') { var hp = ms.slice().reverse(), pgs2 = Math.max(1, Math.ceil(hp.length / 30)); return card('📅 Historique', hp.slice(S.page * 30, S.page * 30 + 30).map(function (m) { return kv(m.date + ' · ' + m.home + ' – ' + m.away, m.hs + '-' + m.as + (m.dateApprox ? ' ⚠️ date approx.' : '')); }).join('') + pager(S.page, pgs2) + prov(ms)); }
    return '';
  }
  function render() {
    var el = document.getElementById('edbRoot'); if (!el) return;
    var s = st(), m = s.meta(), all = s.played({}), ms = s.played(Object.assign(filt(), S.team.trim() && S.sec !== 'h2h' && S.sec !== 'teams' && S.sec !== 'form' && S.sec !== 'trends' && S.sec !== 'ha' ? { team: S.team.trim() } : {}));
    var h = '<div class="pro-card"><h3>📊 EA DATABASE ' + (m.state === 'READY' ? '🟢 READY' : '⚪ VIDE') + '</h3>' + kv('Version', esc(m.name)) + kv('Dernière mise à jour', esc(m.lastUpdate ? m.lastUpdate.slice(0, 10) : '—')) + kv('Dernier match traité', esc(m.lastProcessed || '—')) + kv('Matchs · équipes · compétitions', m.matches + ' · ' + m.teams + ' · ' + m.competitions) + (m.quarantined ? kv('⚠️ Quarantaine (anomalies)', m.quarantined) : '')
      + '<p class="pro-dim">Source : ' + esc(D.provider.name) + ' · fonctionne hors connexion.</p><button class="pro-btn" onclick="EA.dbui.rebuild()">Reconstruire depuis l\'historique</button> <button class="pro-btn" onclick="EA.dbui.fullRebuild()">FULL REBUILD (réparation)</button></div>';
    h += '<div class="pro-card"><h3>Importer des matchs (CSV)</h3><textarea class="pro-in" id="edbCsv" rows="3" placeholder="date;domicile;extérieur;compétition;saison;hs;as;corners_h;corners_a;sot_h;sot_a">' + esc(S.csv) + '</textarea><button class="pro-btn" onclick="EA.dbui.importCsv()">Importer</button><p class="pro-dim">Colonnes facultatives : shots_h/a, sot_h/a, corners_h/a, cards_h/a, xg_h/a… Une cellule vide reste UNKNOWN.</p></div>';
    if (S.log) h += '<div class="pro-card"><h3>INITIALISATION DATABASE</h3><p>' + '█'.repeat(S.log.steps.length > 10 ? 10 : S.log.steps.length) + '░'.repeat(10 - Math.min(10, S.log.steps.length)) + ' ' + Math.min(100, Math.round(S.log.steps.length / 11 * 100)) + ' %</p><p>' + (S.log.error ? '⚠️ ' + esc(S.log.error) + (S.log.restored ? ' → RESTORE PREVIOUS STATE (base précédente conservée)' : '') : S.log.ready ? '━━━━━━━━━━━━<br>🟢 EA DATABASE READY<br>━━━━━━━━━━━━' : '⚪ aucune donnée') + '</p>' + S.log.steps.map(function (x) { return kv('✓ ' + x.step, esc(x.detail)); }).join('') + '</div>';
    h += '<div class="pro-card"><h3>Filtres</h3><div class="pro-fields">' + '<select class="pro-in" id="edbSport">' + opts(['football', 'basketball'], S.sport, 'Sport') + '</select><select class="pro-in" id="edbComp">' + opts(uniq(all, 'competition'), S.comp, 'Compétition') + '</select><select class="pro-in" id="edbSeason">' + opts(uniq(all, 'season'), S.season, 'Saison') + '</select>'
      + '<input class="pro-in" id="edbTeam" placeholder="Équipe" value="' + esc(S.team) + '"><input class="pro-in" id="edbTeam2" placeholder="Adversaire (H2H)" value="' + esc(S.team2) + '"><select class="pro-in" id="edbVenue">' + opts(['home', 'away'], S.venue, 'Dom./Ext.') + '</select><input class="pro-in" id="edbLast" inputmode="numeric" placeholder="Nb de matchs" value="' + esc(S.last) + '"></div></div>';
    var secs = [['overview', '🗂 Aperçu'], ['comp', '📚 Compétitions'], ['teams', '⚽ Équipes'], ['goals', '🥅 Buts'], ['btts', '🎯 BTTS'], ['ou', '📈 Over/Under'], ['ha', '🏠 Dom./Ext.'], ['corners', '🚩 Corners'], ['sot', '🎯 Tirs cadrés'], ['shots', '🎯 Tirs'], ['form', '📊 Formes'], ['h2h', '🔎 H2H'], ['hist', '📅 Historique'], ['trends', '🧠 Tendances'], ['base', '📏 Baselines'], ['quality', '✅ Qualité'], ['inputs', '🧪 Analyse'], ['health', '🩺 Santé'], ['journal', '🧾 Journal'], ['errors', '🧠 Erreurs'], ['search', '🔎 Recherche']];
    secs = secs.concat((EA.dbui && EA.dbui.extraSecs) || []);
    h += '<div class="pro-row" style="flex-wrap:wrap;gap:6px">' + secs.map(function (x) { return '<button class="pro-btn small' + (S.sec === x[0] ? ' active' : '') + '" data-edbsec="' + x[0] + '">' + x[1] + '</button>'; }).join('') + '</div>' + safeSection(ms);
    el.innerHTML = h;
    var bind = function (id, key, redo) { var e = document.getElementById(id); if (e) e.addEventListener(redo ? 'change' : 'change', function () { S[key] = e.value; render(); }); };
    bind('edbSport', 'sport'); bind('edbComp', 'comp'); bind('edbSeason', 'season'); bind('edbTeam', 'team'); bind('edbTeam2', 'team2'); bind('edbVenue', 'venue'); bind('edbLast', 'last'); bind('edbQ', 'q'); bind('edbQ2', 'q');
    Array.prototype.forEach.call(el.querySelectorAll('[data-edbsec]'), function (b) { b.addEventListener('click', function () { S.sec = b.getAttribute('data-edbsec'); S.page = 0; render(); }); });
    Array.prototype.forEach.call(el.querySelectorAll('[data-edbpage]'), function (b) { b.addEventListener('click', function () { S.page = Math.max(0, +b.getAttribute('data-edbpage')); render(); }); });
    Array.prototype.forEach.call(el.querySelectorAll('[data-edbset]'), function (b) { b.addEventListener('click', function () { var p = b.getAttribute('data-edbset').split(':'), k = p.shift(), v = p.join(':'); if (k === 'team') { S.team = v; S.sec = 'teams'; } else if (k === 'comp') { S.comp = v; S.sec = 'comp'; } else if (k === 'season') { S.season = v; S.sec = 'comp'; } render(); }); });
  }
  function legacyDB() { try { var s = JSON.parse(g.localStorage.getItem('ea_v3_store')); if (s && s.football) return s; } catch (e) { } return typeof DB !== 'undefined' ? DB : null; }   // lit le stockage persistant : indépendant du moment où l'app charge son historique
  function sources() { var rows = D.fromLegacy(legacyDB()), mem = []; try { var raw = JSON.parse(g.localStorage.getItem('ea_pro_memory')); mem = D.fromMemory(raw && raw.analyses || []); } catch (e) { } return [{ name: 'LEGACY-HISTORY', rows: rows }, { name: 'EA-MEMORY', rows: mem }]; }
  function hooks() { var recs = proRecs(); return { models: function () { return EA.market ? Object.keys(EA.market.perf(recs)).length + ' marché(s) suivis (modèles réels : voir 🧰 Moteurs)' : 'n/a'; }, calibrate: function () { return EA.calibration ? EA.calibration.buckets(recs).n + ' observation(s) de calibration' : 'n/a'; } }; }
  function rebuild() { try { S.log = st().initialize(sources()); } catch (e) { S.log = { steps: [], ready: false, error: e.message }; } render(); }
  function fullRebuild() { try { S.log = st().fullRebuild(sources(), Date.now(), hooks()); } catch (e) { S.log = { steps: [], ready: false, error: e.message, restored: true }; } render(); }
  function importCsv() { var t = document.getElementById('edbCsv'); S.csv = t ? t.value : ''; var rows = D.parseCSV(S.csv); S.log = st().initialize([{ rows: rows }]); if (S.log.ready) S.csv = ''; render(); }
  function mount() {
    if (document.getElementById('view-edb')) return;
    var tabs = document.querySelector('.tab[data-tab="pro"]'), v = document.querySelector('.view'); if (!tabs || !v) return;
    var b = document.createElement('button'); b.className = 'tab sfx-tab'; b.setAttribute('data-tab', 'edb'); b.innerHTML = '<span class="ic">📊</span>EA DATABASE'; tabs.parentNode.insertBefore(b, tabs.nextSibling);
    var sec = document.createElement('section'); sec.id = 'view-edb'; sec.className = 'view'; sec.innerHTML = '<div id="edbRoot"></div>'; v.parentNode.appendChild(sec);
    b.addEventListener('click', function () {
      Array.prototype.forEach.call(document.querySelectorAll('.tab'), function (x) { x.classList.remove('active'); }); Array.prototype.forEach.call(document.querySelectorAll('.view'), function (x) { x.classList.remove('active'); }); b.classList.add('active'); sec.classList.add('active');
      var m = st().meta(); if (m.state !== 'READY') { var rows = sources(); if (rows[0].rows.length || rows[1].rows.length) S.log = st().initialize(rows); } else { var r = st().upsert(sources().reduce(function (a, x) { return a.concat(x.rows); }, [])); }   // mise à jour incrémentale
      requestAnimationFrame(render);
    });
  }
  function analyze() { var v = function (id) { var e = document.getElementById(id); return e ? e.value.trim() : ''; }; S.inp = { home: v('edbH'), away: v('edbA'), market: v('edbM') || 'over:2.5', p: v('edbP'), odds: v('edbO'), oo: v('edbOO') };
    var num = function (x) { var n = parseFloat(String(x).replace(',', '.')); return isFinite(n) ? n : null; }, P = num(S.inp.p);
    S.analysis = EA.dbintel.analyze(st(), { sport: S.sport || 'football', competition: S.comp || undefined, home: S.inp.home, away: S.inp.away, market: S.inp.market, modelP: P == null ? null : P / 100, odds: num(S.inp.odds), oddsOther: S.inp.oo.split(/[;,\s]+/).map(num).filter(function (x) { return x != null; }) }); st().log('MODEL', 'Analyse ' + S.inp.home + ' – ' + S.inp.away + ' · ' + S.inp.market + ' → ' + S.analysis.decision); st().saveNow(); render(); }
  EA.dbui = { h: { esc: esc, kv: kv, card: card, pct: pct, a2: a2, prov: prov, pager: pager, S: S, st: st, render: render, proRecs: proRecs, filt: filt, rowsR: rowsR }, fullRebuild: fullRebuild, extra: {}, extraSecs: [], setSection: function (x) { S.sec = x; S.page = 0; render(); }, analyze: analyze, sources: sources, rebuild: rebuild, importCsv: importCsv, render: render, store: st };
  function injectStyle() { if (document.getElementById('edbStyle')) return; var s = document.createElement('style'); s.id = 'edbStyle'; s.textContent = '#edbRoot{max-width:100%;overflow-x:hidden}#edbRoot .pro-kv span{overflow-wrap:anywhere}#edbRoot .pro-btn{min-height:40px}#edbRoot .pro-fields{display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:8px}#edbRoot details{margin:6px 0}#edbRoot summary{cursor:pointer;padding:6px 0;overflow-wrap:anywhere}#edbRoot textarea.pro-in{min-height:84px}'; try { (document.head || document.documentElement).appendChild(s); } catch (e) { } }
  function autoSync() { try { var src = sources(), rows = src.reduce(function (a, x) { return a.concat(x.rows); }, []); if (!rows.length) return; if (st().meta().state !== 'READY') st().initialize(src); else st().upsert(rows); } catch (e) { try { st().log('ERROR', 'Mise à jour automatique : ' + e.message); st().saveNow(); } catch (e2) { } } }
  function boot() { injectStyle(); setTimeout(autoSync, 1500); setTimeout(autoSync, 6000); }
  if (document.readyState === 'loading') { document.addEventListener('DOMContentLoaded', mount); document.addEventListener('DOMContentLoaded', boot); } else { mount(); boot(); }
})(typeof window !== 'undefined' ? window : global);
